### ISSUE TITLE
actionMenu.close(false) generates null view from zip sources

### ISSUE THREAD

**Issue by ntorvik** [oguzbilgener/CircularFloatingActionMenu#44]
When I include the library via gradle everything runs fine.   When I download the .zip sources and manually include the library, everything compiles and works correctly except when I click on a submenu button it generates following error:

java.lang.IllegalArgumentException: view must not be null
            at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:324)
            at android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:79)
            at com.oguzdev.circularfloatingactionmenu.library.FloatingActionMenu.detachOverlayContainer(FloatingActionMenu.java:477)
            at com.oguzdev.circularfloatingactionmenu.library.FloatingActionMenu.close(FloatingActionMenu.java:244)

If i set my actionMenu.close(true) it works, but this is not the behavior I was wanting.

Is there something different about the sources on github -vs- the ones pulled down from maven?

**Comment by girish3** [comment]
+1
