### ISSUE TITLE
Getting NullPointerException 

### ISSUE THREAD

**Issue by X-509** [oguzbilgener/CircularFloatingActionMenu#62]
I have a submethod in onCreate which creates the floating button menu. here is the code

    private void createFloatingButton() {
        SubActionButton.Builder itemBuilder = new SubActionButton.Builder(this);
        ImageView itemIcon = new ImageView(this);

        itemIcon.setImageDrawable( getResources().getDrawable(R.mipmap.ic_file, getTheme()));
        SubActionButton button1 = itemBuilder.setContentView(itemIcon).build();

//        SubActionButton newFolder = itemBuilder.setContentView(icon).build();
//        SubActionButton copy = itemBuilder.setContentView(icon).build();
//        SubActionButton cut = itemBuilder.setContentView(icon).build();
//        SubActionButton paste = itemBuilder.setContentView(icon).build();
//        SubActionButton delete = itemBuilder.setContentView(icon).build();

        FloatingActionMenu actionMenu = new FloatingActionMenu.Builder(this)
                .addSubActionView(button1)
//                .addSubActionView(newFolder)
//                .addSubActionView(copy)
//                .addSubActionView(cut)
//                .addSubActionView(paste)
//                .addSubActionView(delete)
                .build();

    }

And the exception that I am getting is 

11-17 20:51:34.767 15383-15383/? E/AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.company.project/com.company.project.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setClickable(boolean)' on a null object reference
11-17 20:51:34.767 15383-15383/? E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
11-17 20:51:34.767 15383-15383/? E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
11-17 20:51:34.767 15383-15383/? E/AndroidRuntime:     at android.app.ActivityThread.access$800(ActivityThread.java:151)
11-17 20:51:34.767 15383-15383/? E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
11-17 20:51:34.767 15383-15383/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
11-17 20:51:34.767 15383-15383/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135)
11-17 20:51:34.767 15383-15383/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5254)
11-17 20:51:34.767 15383-15383/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
11-17 20:51:34.767 15383-15383/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
11-17 20:51:34.767 15383-15383/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
11-17 20:51:34.767 15383-15383/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
11-17 20:51:34.767 15383-15383/? E/AndroidRuntime:  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setClickable(boolean)' on a null object reference
11-17 20:51:34.767 15383-15383/? E/AndroidRuntime:     at com.oguzdev.circularfloatingactionmenu.library.FloatingActionMenu.<init>(FloatingActionMenu.java:81)
11-17 20:51:34.767 15383-15383/? E/AndroidRuntime:     at com.oguzdev.circularfloatingactionmenu.library.FloatingActionMenu$Builder.build(FloatingActionMenu.java:495)
11-17 20:51:34.767 15383-15383/? E/AndroidRuntime:     at com.kreatives.kube3.MainActivity.createFloatingButton(MainActivity.java:102)
11-17 20:51:34.767 15383-15383/? E/AndroidRuntime:     at com.kreatives.kube3.MainActivity.onCreate(MainActivity.java:79)
11-17 20:51:34.767 15383-15383/? E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:5990)
11-17 20:51:34.767 15383-15383/? E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
11-17 20:51:34.767 15383-15383/? E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
11-17 20:51:34.767 15383-15383/? E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
11-17 20:51:34.767 15383-15383/? E/AndroidRuntime:     at android.app.ActivityThread.access$800(ActivityThread.java:151) 
11-17 20:51:34.767 15383-15383/? E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
11-17 20:51:34.767 15383-15383/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102) 
11-17 20:51:34.767 15383-15383/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135) 
11-17 20:51:34.767 15383-15383/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5254) 
11-17 20:51:34.767 15383-15383/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method) 
11-17 20:51:34.767 15383-15383/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372) 
11-17 20:51:34.767 15383-15383/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
11-17 20:51:34.767 15383-15383/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by kamran1** [comment]
Any Solution
